# Generated by Django 4.2.5 on 2023-09-24 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store_app', '0009_cartitem'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CartItem',
        ),
    ]
