# Generated by Django 4.2.5 on 2023-10-14 22:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store_app', '0012_order_paid_order_payment_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='city',
            new_name='fullname',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='address',
            new_name='product_info',
        ),
        migrations.RemoveField(
            model_name='order',
            name='country',
        ),
        migrations.RemoveField(
            model_name='order',
            name='firstname',
        ),
        migrations.RemoveField(
            model_name='order',
            name='lastname',
        ),
        migrations.RemoveField(
            model_name='order',
            name='postcode',
        ),
        migrations.RemoveField(
            model_name='order',
            name='state',
        ),
    ]
