# Generated by Django 4.2.5 on 2023-10-15 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store_app', '0016_varient_test_product_varient_test'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='varient_test',
        ),
    ]
