# Generated by Django 4.2.5 on 2023-10-30 16:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('store_app', '0018_product_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('Publish', 'Publish'), ('Draft', 'Draft')], max_length=50)),
                ('categories', models.ManyToManyField(to='store_app.categories')),
                ('images', models.ManyToManyField(blank=True, to='store_app.images')),
                ('tags', models.ManyToManyField(to='store_app.tag')),
            ],
        ),
    ]
