# Generated by Django 4.2.5 on 2023-11-06 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_app', '0022_orderitem_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(max_length=200, null=True, unique=True),
        ),
    ]
