# Generated by Django 4.2.5 on 2023-11-06 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_app', '0023_alter_product_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComboProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField()),
                ('products', models.ManyToManyField(to='store_app.product')),
                ('variants', models.ManyToManyField(to='store_app.varient_test')),
            ],
        ),
    ]
