# Generated by Django 4.2.5 on 2023-11-07 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_app', '0024_comboproduct'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComboOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('price', models.IntegerField()),
                ('products', models.ManyToManyField(blank=True, related_name='combo_offer_as_primary', to='store_app.product')),
            ],
        ),
        migrations.DeleteModel(
            name='ComboProduct',
        ),
        migrations.AddField(
            model_name='product',
            name='combo_products',
            field=models.ManyToManyField(blank=True, related_name='combo_offer_as_secondary', to='store_app.combooffer'),
        ),
    ]
