# Generated by Django 4.2.5 on 2023-11-10 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_app', '0025_combooffer_delete_comboproduct_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='combooffer',
            name='image',
            field=models.ImageField(blank=True, upload_to='product_images/img'),
        ),
    ]
